### PR TITLE
refactor: include stack for `onError`

### PR DESCRIPTION
**Pull request by tenshiAMD**
**What**: 
- Fixes https://github.com/all-contributors/cli/issues/312. 

CC @JoshuaKGoldberg 

**Why**:
- Better log insight.

**How**:
- Update implementation for `onError`

**Checklist**:

- [x] Documentation
- [x] Tests
- [x] Ready to be merged 
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by tenshiAMD** [comment]
@all-contributors please add @JoshuaKGoldberg for bug

**Comment by JoshuaKGoldberg** [comment]
Super, thanks for sending this in @tenshiAMD!

As a very small quick point of feedback: I wish I'd been given more than 5 hours from the time #312 was accepted _("sure you're welcome to send a PR for this one")_ to get my own PR in. I was excited to contribute but was asleep during those 5 hours.

**Comment by tenshiAMD** [comment]
@JoshuaKGoldberg I'm really sorry man. Anyways, I can close this PR then I will wait for your PR. Thanks 🎉

**Comment by JoshuaKGoldberg** [comment]
Oh amazing, thanks! I appreciate it ❤️

**Pull request closed without merging**
