### PR TITLE
feat: add `wrapperTemplate` option

### PR DESCRIPTION
**Pull request by jdalrymple**
**What**: Adding support for a wrapper template that allows for a minimalist version of the contributors log. See original [issue](https://github.com/all-contributors/all-contributors/issues/85)

**Why**: Modified the wrapping template from the defaulted 'table' to what ever the user supplies in their configuration

**How**: A simple if during the generation of the list wrapping. For a working sample, check this [repo](https://github.com/jdalrymple/all-contributors-wrapper-sample). After running the install, you may need to run `yarn build` from within the node_modules/all-contributors-cli directory to have access to the cli commands.

**Checklist**:

- [x] [Documentation](https://github.com/all-contributors/all-contributors/pull/673)
- [x] Tests
- [x] Ready to be merged 
- [ ] Added myself to contributors table

### CODE REVIEW

**Comment by jdalrymple** [comment]
Posted the PR to look for any feedback while i fill in the rest of the checklist!

**Comment by jdalrymple** [comment]
Silly question, but where should I be updating the docs/tests? :thinking:

**Comment by jdalrymple** [comment]
Where are the docs located? :thinking:

**Comment by tenshiAMD** [comment]
> Where are the docs located? 🤔

@jdalrymple docs are in https://github.com/all-contributors/all-contributors.

**Review by tenshiAMD — CHANGES_REQUESTED** [review]
@jdalrymple Thanks for this contribution. Please provide a working example for this one so we can compare. Also, I'm unsure about using other parent tags besides `<table>`. We also need to check the browser compatible.

**Comment by jdalrymple** [comment]
Can do! The primary reason for the option to change the wrapper tag is because of the styling limitations within markdown linked to the table tag. For example in that issue, the desire to have a minimalist list of contributors such as:

image

Can only be accomplished with either styling (which isnt supported in github markdown) or changing the tag used to wrap the content. I was able to accomplish this example with p tag instead of the table tag, however knowing that things should not be hardcoded, i figured using a configurable option would be the way to go. Ill post up a sample repo ASAP!

**Comment by jdalrymple** [comment]
The only caveat** Is the number of contributors per line. Need to think of a good way to support that with different wrapper tags

**Review by Berkmann18 — APPROVED** [review]

**Comment by jdalrymple** [comment]
Is there anything else that i need to address for this to be merged?

**Review by gr2m — APPROVED** [review]
Thank you for the pull request! Sorry for the delay!

**Comment by gr2m** [comment]
@all-contributors add @jdalrymple for code and test

**Pull request merged**
