### PR TITLE
fix: correct escape quotes in contributor names

### PR DESCRIPTION
**Pull request by dwmkerr**
**What**:

This PR fixes issue #352

**Why**:

Quote in GitHub user names create invalid HTML in the contributors table

**How**:

Expanding on the technique used to fix pipes in names.

**Checklist**:
- [x] Documentation (na)
- [X] Tests
- [X] Ready to be merged 
- [X] Added myself to contributors table

### CODE REVIEW

**Comment by dwmkerr** [comment]
@all-contributors add dwmkerr for bug tests code

**Comment by dwmkerr** [comment]
Hey all any updates on when we can get this in? It's a bit of a challenge for my colleagues which special characters in names

**Review by gr2m — APPROVED** [review]
Thank you! Sorry for the wait

**Comment by dwmkerr** [comment]
Great, thanks @gr2m !

**Pull request merged**
